"""
Group of functions to print the paired comparison of ARIMAX, the neighbour regression and the
two-stage regression with SARIMA errors (src/evaluation/paired_comparison.py).

python -m src.plotting.plot_paired_comparison
"""
from src.evaluation.paired_comparison import compare
from src.plotting.plot_short_horizon_comparison import load_results, MODEL_NAMES, OUTPUT_DIR

# Pairs of models to compare, the neighbour regression as the reference for the two models that
# extend it, plus the two error models against each other
CONTRASTS = [
    ("RegressionSARIMAErrors", "LinearRegression"),
    ("ARIMAX", "LinearRegression"),
    ("RegressionSARIMAErrors", "ARIMAX"),
]

# Forecast hours the comparison is reported at
LEADS = [1, 2, 4, 8, 12, 24, 48, 96]


def contrast_label(model, reference):
    """
    Name of a contrast as used in the plots and the printed tables.

    Input
    -----
    model: Key of the model being compared
    reference: Key of the model it is compared against

    Output
    ------
    Returns the two model names separated by a minus sign.
    """
    return f"{MODEL_NAMES[model]} - {MODEL_NAMES[reference]}"


def format_p_value(p_value):
    """
    Format a p value, showing the resolution of the sign flip test rather than a misleading zero.

    Input
    -----
    p_value: The raw or the adjusted p value

    Output
    ------
    Returns the p value as a string.
    """
    return "<0.001" if p_value < 0.001 else f"{p_value:.3f}"


def print_comparison(results, title):
    """
    Print one comparison as a table, one line per contrast and forecast hour.

    Input
    -----
    results: DataFrame as returned by compare
    title: Heading printed above the table
    """
    print(f"\n=== {title} ===")
    print("The interval covers one contrast at one forecast hour, the adjusted p value covers every "
          "forecast hour of that contrast, so the two can disagree")
    print(f"{'Leads':>8}{'Difference':>13}{'95% interval':>22}{'p':>9}{'p (Holm)':>11}"
          f"{'Wins':>7}   Contrast")

    for _, row in results.iterrows():
        interval = f"[{row['Lower']:+.4f}, {row['Upper']:+.4f}]"
        print(f"{row['Leads']:>8}{row['Difference']:>+13.4f}{interval:>22}"
              f"{format_p_value(row['P_value']):>9}{format_p_value(row['P_holm']):>11}"
              f"{row['Win_rate']:>7.0%}   "
              f"{contrast_label(row['Model'], row['Reference'])}")


if __name__ == "__main__":
    # Load all the csv files generated by the short horizon comparison experiment
    df = load_results(OUTPUT_DIR)

    print(f"{len(df)} rows, {df['Station'].nunique()} stations, "
          f"{df['Train_start'].nunique()} forecast starts")

    # The error at one forecast hour, which is where the models actually differ
    per_lead = compare(df, CONTRASTS, [(lead, [lead]) for lead in LEADS])
    print_comparison(per_lead, "Paired difference at one forecast hour (°C)")

    # The error averaged over the whole forecast, matching the cumulative figure
    cumulative = compare(df, CONTRASTS, [(lead, range(1, lead + 1)) for lead in LEADS])
    print_comparison(cumulative, "Paired difference over the whole forecast window (°C)")
