"""
Group of functions to plot the short horizon comparison of ARIMAX, the neighbour regression and the
two-stage regression with SARIMA errors (src/scripts/short_horizon_comparison_experiment.py).
The plots are saved in the "plots/short_horizon_comparison" directory for further analysis and presentation.

python -m src.plotting.plot_short_horizon_comparison
"""
import os
import pandas as pd
import matplotlib.pyplot as plt

# Model keys as written in the result csv files -> the names used in the plots, matching the names
# used for the results table in src/plotting/plot_model_comparisons.py
MODEL_NAMES = {
    "LinearRegression": "Neighbour regression",
    "RegressionSARIMAErrors": "Regression + SARIMA errors",
    "ARIMAX": "ARIMAX",
}

# Fixed colour per model, so a model keeps its colour across every figure
MODEL_COLOURS = {
    "LinearRegression": "#1baf7a",
    "RegressionSARIMAErrors": "#2a78d6",
    "ARIMAX": "#eb6834",
}

# Directory holding the result csv files and the directory the figures are written to
OUTPUT_DIR = "output/short_horizon_comparison"
PLOT_DIR = "plots/short_horizon_comparison"


def load_results(output_dir):
    """
    Load and concatenate the per-model result files of the short horizon experiment.

    Input:
    ------
    output_dir: Directory holding the result csv files

    Output:
    -------
    Returns a DataFrame with all results (columns: Dataset, Station, Model, Train_start, Train_end,
    Horizon, MAE, MSE, Train_duration_seconds, Forecast_duration_seconds).
    """
    csv_files = [
        os.path.join(output_dir, f)
        for f in os.listdir(output_dir)
        if f.endswith("8_weeks.csv")
    ]

    return pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)


def plot_cumulative_mae(df, plot_dir):
    """
    1. Plot the MAE against the forecast horizon, averaged over all datasets, stations and training periods.

    Input:
    ------
    df: DataFrame containing all the results, as returned by load_results
    plot_dir: Directory to write the figure to
    """
    summary = df.groupby(["Model", "Horizon"])["MAE"].mean()
    horizons = sorted(df["Horizon"].unique())

    plt.figure(figsize=(8, 5))

    for model in MODEL_NAMES:
        plt.plot(
            horizons, [summary[model, h] for h in horizons],
            marker="o", color=MODEL_COLOURS[model], label=MODEL_NAMES[model]
        )

    # The horizons are spaced geometrically, so a log axis keeps the short leads readable
    plt.xscale("log")
    plt.xticks(horizons, [str(h) for h in horizons])
    plt.xlabel("Forecast horizon (hours)")
    plt.ylabel("Mean absolute error (°C)")
    plt.title("Error averaged over the whole forecast window")
    plt.grid(alpha=0.3)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(plot_dir, "cumulative_mae_vs_horizon.png"), dpi=200)
    plt.close()

    print("\n=== Mean absolute error per horizon (°C) ===")
    print(f"{'Horizon (h)':<14}" + "".join(f"{MODEL_NAMES[m]:>30}" for m in MODEL_NAMES))
    for horizon in horizons:
        print(f"{horizon:<14}" + "".join(f"{summary[m, horizon]:>30.4f}" for m in MODEL_NAMES))


if __name__ == "__main__":
    # Load all the csv files generated by the short horizon comparison experiment
    df = load_results(OUTPUT_DIR)

    print(f"{len(df)} rows, {df['Station'].nunique()} stations, "
          f"{df['Train_start'].nunique()} training periods")

    # Create plot directory if it does not exist
    os.makedirs(PLOT_DIR, exist_ok=True)

    plot_cumulative_mae(df, PLOT_DIR)
