from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt


def generate_lasso_summary_table(df):
    """
    Generate LaTeX summary table comparing:
        - All stations
        - LASSO selection

    Input:
    ------
    df: DataFrame containing the results of the LASSO selection experiment, with columns:
        - target_station
        - all_mae
        - optimal_mae
        - mae_difference
        - nr_stations
        - duration_all_seconds
        - duration_lasso_selection_seconds
        - duration_lasso_forecast_seconds
    """
    # Derived metrics
    df = df.copy()

    df["lasso_total_seconds"] = df["duration_lasso_selection_seconds"] + df["duration_lasso_forecast_seconds"]
    df["speedup"] = df["duration_all_seconds"] / df["lasso_total_seconds"]

    # Aggregate statistics
    summary = pd.DataFrame({
        "Setting": ["Alle stations", "LASSO selectie"],

        "mae_mean": [
            df["all_mae"].mean(),
            df["optimal_mae"].mean()
        ],
        "mae_std": [
            df["all_mae"].std(),
            df["optimal_mae"].std()
        ],

        "runtime_mean": [
            df["duration_all_seconds"].mean(),
            df["lasso_total_seconds"].mean()
        ],
        "runtime_std": [
            df["duration_all_seconds"].std(),
            df["lasso_total_seconds"].std()
        ],
    })

    # Extra LASSO-only metrics
    mean_nr_stations = df["nr_stations"].mean()
    mean_selection_time = df["duration_lasso_selection_seconds"].mean()
    mean_forecast_time = df["duration_lasso_forecast_seconds"].mean()
    mean_speedup = df["speedup"].mean()

    # Formatting helpers
    best_mae = summary["mae_mean"].min()
    best_runtime = summary["runtime_mean"].min()

    def format_value(mean, std, best):
        value = f"{mean:.3f} ± {std:.3f}"
        return f"\\textbf{{{value}}}" if mean == best else value

    summary["MAE"] = summary.apply(
        lambda r: format_value(r.mae_mean, r.mae_std, best_mae),
        axis=1
    )

    summary["Runtime (s)"] = summary.apply(
        lambda r: format_value(r.runtime_mean, r.runtime_std, best_runtime),
        axis=1
    )

    summary_table = summary[["Setting", "MAE", "Runtime (s)"]]

    # Generate LaTeX
    latex_code = summary_table.to_latex(
        index=False,
        escape=False,
        column_format="lcc"
    )

    # Add extra informative rows manually
    extra_rows = f"""
    \\\\
    \\midrule
    \\multicolumn{{3}}{{l}}{{\\textit{{Totaal aantal beschikbare stations}}: {48}}} \\\\
    \\multicolumn{{3}}{{l}}{{\\textit{{Gemiddeld aantal geselecteerde stations}}: {mean_nr_stations:.1f}}} \\\\
    \\multicolumn{{3}}{{l}}{{\\textit{{LASSO selectietijd}}: {mean_selection_time:.2f} s}} \\\\
    \\multicolumn{{3}}{{l}}{{\\textit{{LASSO voorspellingstijd}}: {mean_forecast_time:.2f} s}} \\\\
    \\multicolumn{{3}}{{l}}{{\\textit{{Gemiddelde speedup}}: {mean_speedup:.1f}$\\times$}} \\\\
    """

    latex_code = latex_code.replace("\\end{tabular}", extra_rows + "\n\\end{tabular}")

    print("\n=== LASSO vs All Stations Summary ===\n")
    print(latex_code)


# Load the result files generated by determine_optimal_nr_stations.py
results_dir = Path("output/LASSO_stations")

files = sorted(results_dir.glob("*.csv"))

if not files:
    raise RuntimeError("No result files found.")

dfs = [pd.read_csv(f) for f in files]
df = pd.concat(dfs, ignore_index=True)

# Derived metrics
# Total LASSO runtime (selection + forecast)
df["duration_lasso_total_seconds"] = (
    df["duration_lasso_selection_seconds"] + df["duration_lasso_forecast_seconds"]
)

# Speedup factor
df["speedup_factor"] = df["duration_all_seconds"] / df["duration_lasso_total_seconds"]

# Time saved
df["time_saved_seconds"] = df["duration_all_seconds"] - df["duration_lasso_total_seconds"]

# Global summary statistics
baseline_mae = df["all_mae"].mean()
optimal_mae = df["optimal_mae"].mean()
mean_improvement = df["mae_difference"].mean()

# Plot 1: MAE improvement
df = df.sort_values("mae_difference", ascending=False)

# Use colors to indicate improvement (green) or worsening (red) compared to using all stations
colors = df["mae_difference"].apply(
    lambda x: "tab:green" if x > 0 else "tab:red"
)

# Plot
plt.figure(figsize=(10, 6))

plt.bar(
    df["target_station"],
    df["mae_difference"],
    color=colors,
    alpha=0.85
)

plt.text(
    0.99, 0.98,
    (
        f"Gemiddelde MAE (alle stations): {baseline_mae:.3f} °C\n"
        f"Gemiddelde MAE (LASSO selectie): {optimal_mae:.3f} °C\n"
        f"Gemiddelde verbetering: {mean_improvement:.3f} °C"
    ),
    transform=plt.gca().transAxes,
    fontsize=11,
    horizontalalignment="right",
    verticalalignment="top",
    bbox=dict(boxstyle="round", alpha=0.5, facecolor="white", edgecolor="gray")
)

# baseline reference
plt.axhline(0, linestyle="--")

plt.ylabel("MAE verbetering ten opzichte van alle stations (°C)")
plt.xlabel("Doelstations (gerangschikt volgens verbetering)")
plt.xticks([])

plt.tight_layout()
plt.savefig("LASSO_selection_improvement.png")
plt.close()

# Generate LaTeX summary table
generate_lasso_summary_table(df)
