"""
Group of functions to plot and print the paired comparison of ARIMAX, the neighbour regression and the
two-stage regression with SARIMA errors (src/evaluation/paired_comparison.py). The plots are saved in
the "plots/short_horizon_comparison" directory for further analysis and presentation.

python -m src.plotting.plot_paired_comparison
"""
import os
import matplotlib.pyplot as plt
from src.evaluation.paired_comparison import compare
from src.plotting.plot_short_horizon_comparison import load_results, MODEL_NAMES, OUTPUT_DIR, PLOT_DIR

# Pairs of models to compare, the neighbour regression as the reference for the two models that
# extend it, plus the two error models against each other
CONTRASTS = [
    ("RegressionSARIMAErrors", "LinearRegression"),
    ("ARIMAX", "LinearRegression"),
    ("RegressionSARIMAErrors", "ARIMAX"),
]

# Fixed colour per contrast, so a contrast keeps its colour across every figure
CONTRAST_COLOURS = {
    ("RegressionSARIMAErrors", "LinearRegression"): "#2a78d6",
    ("ARIMAX", "LinearRegression"): "#eb6834",
    ("RegressionSARIMAErrors", "ARIMAX"): "#1baf7a",
}

# Forecast hours the comparison is reported at
LEADS = [1, 2, 4, 8, 12, 24, 48, 96]


def contrast_label(model, reference):
    """
    Name of a contrast as used in the plots and the printed tables.

    Input
    -----
    model: Key of the model being compared
    reference: Key of the model it is compared against

    Output
    ------
    Returns the two model names separated by a minus sign.
    """
    return f"{MODEL_NAMES[model]} - {MODEL_NAMES[reference]}"


def format_p_value(p_value):
    """
    Format a p value, showing the resolution of the sign flip test rather than a misleading zero.

    Input
    -----
    p_value: The raw or the adjusted p value

    Output
    ------
    Returns the p value as a string.
    """
    return "<0.001" if p_value < 0.001 else f"{p_value:.3f}"


def print_comparison(results, title):
    """
    Print one comparison as a table, one line per contrast and forecast hour.

    Input
    -----
    results: DataFrame as returned by compare
    title: Heading printed above the table
    """
    print(f"\n=== {title} ===")
    print("The interval covers one contrast at one forecast hour, the adjusted p value covers every "
          "forecast hour of that contrast, so the two can disagree")
    print(f"{'Leads':>8}{'Difference':>13}{'95% interval':>22}{'p':>9}{'p (Holm)':>11}"
          f"{'Wins':>7}   Contrast")

    for _, row in results.iterrows():
        interval = f"[{row['Lower']:+.4f}, {row['Upper']:+.4f}]"
        print(f"{row['Leads']:>8}{row['Difference']:>+13.4f}{interval:>22}"
              f"{format_p_value(row['P_value']):>9}{format_p_value(row['P_holm']):>11}"
              f"{row['Win_rate']:>7.0%}   "
              f"{contrast_label(row['Model'], row['Reference'])}")


def plot_difference_per_lead(results, plot_dir):
    """
    1. Plot the paired difference in mean absolute error against the forecast hour, with the
       confidence interval of every point and a line at zero for equal performance.

    Input
    -----
    results: DataFrame as returned by compare, holding one row per contrast and forecast hour
    plot_dir: Directory to write the figure to
    """
    plt.figure(figsize=(8, 5))
    plt.axhline(0, color="#5f6b7d", linewidth=1)

    for model, reference in CONTRASTS:
        rows = results[(results["Model"] == model) & (results["Reference"] == reference)]
        errors = [rows["Difference"] - rows["Lower"], rows["Upper"] - rows["Difference"]]

        plt.errorbar(
            rows["Leads"], rows["Difference"], yerr=errors,
            marker="o", capsize=3, color=CONTRAST_COLOURS[(model, reference)],
            label=contrast_label(model, reference)
        )

    # The difference is concentrated in the first hours, so a log axis keeps the short leads readable
    plt.xscale("log")
    plt.xticks(LEADS, [str(lead) for lead in LEADS])
    plt.xlabel("Forecast hour")
    plt.ylabel("Difference in mean absolute error (°C)")
    plt.title("Paired difference per forecast hour, negative means the first model is better")
    plt.grid(alpha=0.3)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(plot_dir, "paired_difference_per_lead.png"), dpi=200)
    plt.close()


if __name__ == "__main__":
    # Load all the csv files generated by the short horizon comparison experiment
    df = load_results(OUTPUT_DIR)

    print(f"{len(df)} rows, {df['Station'].nunique()} stations, "
          f"{df['Train_start'].nunique()} forecast starts")

    # Create plot directory if it does not exist
    os.makedirs(PLOT_DIR, exist_ok=True)

    # The error at one forecast hour, which is where the models actually differ
    per_lead = compare(df, CONTRASTS, [(lead, [lead]) for lead in LEADS])
    print_comparison(per_lead, "Paired difference at one forecast hour (°C)")
    plot_difference_per_lead(per_lead, PLOT_DIR)

    # The error averaged over the whole forecast, matching the cumulative figure
    cumulative = compare(df, CONTRASTS, [(lead, range(1, lead + 1)) for lead in LEADS])
    print_comparison(cumulative, "Paired difference over the whole forecast window (°C)")
