"""
Group of functions to plot the short horizon comparison of ARIMAX, the neighbour regression and the
two-stage regression with SARIMA errors (src/scripts/short_horizon_comparison_experiment.py).
The plots are saved in the "plots/short_horizon_comparison" directory for further analysis and presentation.

python -m src.plotting.plot_short_horizon_comparison
"""
import os
import pandas as pd
import matplotlib.pyplot as plt

# Model keys as written in the result csv files -> the names used in the plots, matching the names
# used for the results table in src/plotting/plot_model_comparisons.py
MODEL_NAMES = {
    "LinearRegression": "Neighbour regression",
    "RegressionSARIMAErrors": "Regression + SARIMA errors",
    "ARIMAX": "ARIMAX",
}

# Fixed colour per model, so a model keeps its colour across every figure
MODEL_COLOURS = {
    "LinearRegression": "#1baf7a",
    "RegressionSARIMAErrors": "#2a78d6",
    "ARIMAX": "#eb6834",
}

# Horizons shown on the x axis, aggregated from the hourly rows of the experiment
HORIZONS = [1, 2, 4, 8, 12, 24, 48, 96]

# Directory holding the result csv files and the directory the figures are written to
OUTPUT_DIR = "output/short_horizon_comparison"
PLOT_DIR = "plots/short_horizon_comparison"


def load_results(output_dir):
    """
    Load and concatenate the per-model result files of the short horizon experiment.

    Input:
    ------
    output_dir: Directory holding the result csv files

    Output:
    -------
    Returns a DataFrame with one row per forecast hour and an added Absolute_error column.
    """
    csv_files = [
        os.path.join(output_dir, f)
        for f in os.listdir(output_dir)
        if f.endswith("8_weeks.csv")
    ]

    df = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)

    return df.assign(Absolute_error=(df["Forecast"] - df["Observation"]).abs())


def cumulative_mae(df):
    """
    Average the absolute error over the first h hours of the forecast, for every horizon h.

    Input:
    ------
    df: DataFrame containing all the results, as returned by load_results

    Output:
    -------
    Returns a DataFrame with the models as rows and the horizons as columns.
    """
    return pd.concat(
        [
            df[df["Lead_hours"] <= horizon].groupby("Model")["Absolute_error"].mean().rename(horizon)
            for horizon in HORIZONS
        ],
        axis=1
    )


def plot_cumulative_mae(summary, plot_dir):
    """
    1. Plot the MAE against the forecast horizon, averaged over all datasets, stations and training periods.

    Input:
    ------
    summary: DataFrame with the models as rows and the horizons as columns, as returned by cumulative_mae
    plot_dir: Directory to write the figure to
    """
    plt.figure(figsize=(8, 5))

    for model in MODEL_NAMES:
        plt.plot(
            HORIZONS, summary.loc[model, HORIZONS],
            marker="o", color=MODEL_COLOURS[model], label=MODEL_NAMES[model]
        )

    # The horizons are spaced geometrically, so a log axis keeps the short leads readable
    plt.xscale("log")
    plt.xticks(HORIZONS, [str(h) for h in HORIZONS])
    plt.xlabel("Forecast horizon (hours)")
    plt.ylabel("Mean absolute error (°C)")
    plt.title("Error averaged over the whole forecast window")
    plt.grid(alpha=0.3)
    plt.legend()

    plt.tight_layout()
    plt.savefig(os.path.join(plot_dir, "cumulative_mae_vs_horizon.png"), dpi=200)
    plt.close()

    print("\n=== Mean absolute error per horizon (°C) ===")
    print(f"{'Horizon (h)':<14}" + "".join(f"{MODEL_NAMES[m]:>30}" for m in MODEL_NAMES))
    for horizon in HORIZONS:
        print(f"{horizon:<14}" + "".join(f"{summary.loc[m, horizon]:>30.4f}" for m in MODEL_NAMES))


if __name__ == "__main__":
    # Load all the csv files generated by the short horizon comparison experiment
    df = load_results(OUTPUT_DIR)

    print(f"{len(df)} rows, {df['Station'].nunique()} stations, "
          f"{df['Train_start'].nunique()} forecast starts")

    # Create plot directory if it does not exist
    os.makedirs(PLOT_DIR, exist_ok=True)

    plot_cumulative_mae(cumulative_mae(df), PLOT_DIR)
