from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator

# Create output directory if it doesn't exist
output_dir = Path("plots/station_selection_8weeks")
output_dir.mkdir(parents=True, exist_ok=True)

# Load the result files generated by determine_optimal_nr_stations.py
results_dir = Path("output/optimal_nr_stations_8weeks")

files = sorted(results_dir.glob("optimal_station_*.csv"))

if not files:
    raise RuntimeError("No result files found.")

dfs = [pd.read_csv(f) for f in files]
df = pd.concat(dfs, ignore_index=True)

# Preprocess the data for plotting
df = df.sort_values("mae_difference", ascending=False)

baseline_mae = df["all_mae"].mean()
optimal_mae = df["optimal_mae"].mean()
mean_improvement = df["mae_difference"].mean()

# Use colors to indicate improvement (green) or worsening (red) compared to using all stations
colors = df["mae_difference"].apply(
    lambda x: "tab:green" if x > 0 else "tab:red"
)

# Plot Figure 1 - MAE improvement per station
plt.figure(figsize=(10, 6))

plt.bar(
    df["target_station"],
    df["mae_difference"],
    color=colors,
    alpha=0.85
)

plt.text(
    0.99, 0.98,
    (
        f"Mean MAE (all stations): {baseline_mae:.3f} °C\n"
        f"Mean MAE (best subset): {optimal_mae:.3f} °C\n"
        f"Mean improvement: {mean_improvement:.3f} °C"
    ),
    transform=plt.gca().transAxes,
    fontsize=12,
    horizontalalignment="right",
    verticalalignment="top",
    bbox=dict(boxstyle="round", alpha=0.5, facecolor="white", edgecolor="gray")
)

# baseline reference
plt.axhline(0, linestyle="--")

plt.ylabel("MAE improvement over using all stations (°C)")
plt.xlabel("Target stations (ranked by improvement)")
plt.xticks([])

plt.tight_layout()
plt.savefig(output_dir / "station_selection_improvement.png")
plt.close()

# Plot Figure 2 - Distribution of optimal number of stations selected
plt.figure(figsize=(10, 6))

min_k = df["optimal_k_mae"].min()
max_k = df["optimal_k_mae"].max()

plt.hist(
    df["optimal_k_mae"],
    bins=range(min_k, max_k + 2),
    alpha=0.85,
    edgecolor="black",
    align="left",
    rwidth=0.8
)

# Guarantee that both the x-axis ticks are visible and the y-axis contains only integer values
ax = plt.gca()

ax.yaxis.set_major_locator(MaxNLocator(integer=True))

plt.xlabel("Optimal number of selected stations")
plt.ylabel("Number of target stations")

plt.tight_layout()
plt.savefig(output_dir / "optimal_number_of_stations_distribution.png")
plt.close()
