import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt


def generate_lasso_properties_table(df, total_stations=48):
    """
    Generate LaTeX table with LASSO selection properties in compact style.
    """

    df = df.copy()

    # Derived metrics
    df["lasso_total_seconds"] = df["duration_lasso_selection_seconds"] + df["duration_lasso_forecast_seconds"]
    df["speedup"] = df["duration_all_seconds"] / df["lasso_total_seconds"]

    # Aggregates
    mean_nr_stations = df["nr_stations"].mean()
    median_nr_stations = df["nr_stations"].median()
    minimum_nr_stations = df["nr_stations"].min()
    maximum_nr_stations = df["nr_stations"].max()

    mean_selection_time = df["duration_lasso_selection_seconds"].mean()
    mean_forecast_time = df["duration_lasso_forecast_seconds"].mean()

    mean_speedup = df["speedup"].mean()

    # Build LaTeX manually
    latex_code = f"""
    \\begin{{tabular*}}{{0.8\\textwidth}}{{l@{{\\extracolsep{{\\fill}}}}c}}
    \\toprule
    \\multicolumn{{2}}{{l}}{{\\textbf{{LASSO selectie-eigenschappen}}}} \\\\
    \\midrule
    Totaal aantal beschikbare stations & {total_stations} \\\\
    Gemiddeld aantal geselecteerde stations & {mean_nr_stations:.1f} \\\\
    Range van geselecteerde stations & {minimum_nr_stations:.0f} - {maximum_nr_stations:.0f} (mediaan: {median_nr_stations:.0f}) \\\\
    \\addlinespace[2pt]
    LASSO selectietijd (s) & {mean_selection_time:.2f} \\\\
    Trainingstijd (s) & {mean_forecast_time:.2f} \\\\
    Gemiddelde snelheidswinst t.o.v. alle stations & $\\times${mean_speedup:.1f} \\\\
    \\bottomrule
    \\end{{tabular*}}
    """

    print("\n=== LASSO Properties Table ===\n")
    print(latex_code)


# Load the result files generated by determine_optimal_nr_stations.py
results_dir = Path("output/LASSO_stations_8weeks_lasso_on_training")

files = sorted(results_dir.glob("*.csv"))

if not files:
    raise RuntimeError("No result files found.")

dfs = [pd.read_csv(f) for f in files]
df = pd.concat(dfs, ignore_index=True)

# Derived metrics
# Total LASSO runtime (selection + forecast)
df["duration_lasso_total_seconds"] = (
    df["duration_lasso_selection_seconds"] + df["duration_lasso_forecast_seconds"]
)

# Speedup factor
df["speedup_factor"] = df["duration_all_seconds"] / df["duration_lasso_total_seconds"]

# Time saved
df["time_saved_seconds"] = df["duration_all_seconds"] - df["duration_lasso_total_seconds"]

# Global summary statistics
baseline_mae = df["all_mae"].mean()
optimal_mae = df["optimal_mae"].mean()
mean_improvement = df["mae_difference"].mean()

# Plot 1: MAE improvement
df = df.sort_values("mae_difference", ascending=False)

# Use colors to indicate improvement (green) or worsening (red) compared to using all stations
colors = df["mae_difference"].apply(
    lambda x: "tab:green" if x > 0 else "tab:red"
)

# Plot
plt.figure(figsize=(10, 6))

plt.bar(
    df["target_station"],
    df["mae_difference"],
    color=colors,
    alpha=0.85
)

plt.text(
    0.99, 0.98,
    (
        f"Gemiddelde MAE (alle stations): {baseline_mae:.3f} °C\n"
        f"Gemiddelde MAE (LASSO selectie): {optimal_mae:.3f} °C\n"
        f"Gemiddelde verbetering: {mean_improvement:.3f} °C"
    ),
    transform=plt.gca().transAxes,
    fontsize=12,
    horizontalalignment="right",
    verticalalignment="top",
    bbox=dict(boxstyle="round", alpha=0.5, facecolor="white", edgecolor="gray")
)

# baseline reference
plt.axhline(0, linestyle="--")

plt.ylabel("MAE verbetering ten opzichte van alle stations (°C)")
plt.xlabel("Doelstations (gerangschikt volgens verbetering)")
plt.xticks([])

plt.tight_layout()
os.makedirs("plots/LASSO", exist_ok=True)
plt.savefig("plots/LASSO/LASSO_selection_improvement_8weeks.png")
plt.close()

# Generate LaTeX summary table
generate_lasso_properties_table(df)
